### ISSUE TITLE
Incorrect error reporting

### ISSUE THREAD

**Issue by tomfurrier** [bitrise-io/steps-xcode-builder#2]
If the project directory does not exist or cannot cd into, the step does not throw an error immediately but continues. It makes tracking down incorrect path/filename issues harder.

**Comment by viktorbenei** [comment]
Fixed

    # --- Switch to project's dir
    print_and_do_command cd "${XCODE_BUILDER_PROJECT_ROOT_DIR_PATH}"
    fail_if_cmd_error "Failed to switch directory to the Project Root Directory"
